export default {
    basic: {
        AQUA: '#7fdbff',
        BLACK: '#111111',
        BLUE: '#0074d9',
        FUCHSIA: '#f012be',
        GRAY: '#aaaaaa',
        GRAY_LIGHT: '#ced6db',
        GRAY_LIGHTEST: '#fbfbff',
        GREEN: '#2ecc40',
        LIME: '#01ff70',
        MAROON: '#85144b',
        NAVY: '#001f3f',
        OLIVE: '#3d9970',
        ORANGE: '#ff851b',
        PURPLE: '#b10dc9',
        RED: '#ff4136',
        SILVER: '#dddddd',
        TEAL: '#39cccc',
        WHITE: '#FFFFFF',
        YELLOW: '#ffdc00',
    },
    theme: {
        BLUE_DARK: '#5680e9',
        BLUE_LIGHT: '#84ceeb',
        BLUE: '#5680e9',
        PURPLE_LIGHT: '#c1c8e4',
        PURPLE: '#8860d0',
    },
}
